apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
